version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-python39"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-r0n3o01zbd5g"
s3_prefix = "sam-app-python39"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
